### ISSUE TITLE
Transfer mode matching

### ISSUE THREAD

**Issue by DanielEWeeks** [kristofg/rifec#16]
With a Connect X2 4GB card, I tried all sorts of different options in the EyeFi Center, and I could not get the transfermode number in the Settings.xml to match what is in the code.  I have

<TransferMode>16387</TransferMode>

and this is stable whether the relay to Flickr is on or not (although it does change if I toggle the video on).

Can the transfermode check just be commented out?  It looks like the rest of the code does not actually use the number stored in the TransferMode space.

Thank you.

**Comment by kristofg** [comment]
Hi!

The transfer mode check is there because we don't want to receive images the user expects to end up on Flickr.  Commenting out the check should allow the program to receive the images.  See also the [Troubleshooting wiki page](https://github.com/kristofg/rifec/wiki/Troubleshooting#unsupported_transfermode).

**Comment by DanielEWeeks** [comment]
Thank you - I confirm that, as expected, commenting out the check does allow the program to receive the images.
